name:
  First Cron Job
 
  # Controls when the workflow will run
on:
  schedule:
    - cron: "30 20 * * 5"
 
      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cron:
    runs-on: ubuntu-latest
    environment: ci
    steps:
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.11'
    - name: Run cron entrypoint
      run: python main.py
